### ISSUE TITLE
Split off testing suite

### ISSUE THREAD

**Issue by benjaminantieau** [benjaminantieau/persispy#7]
We should split of the testing suite to make a new package focused on running statistical tests on random graphs and random simplicial complexes and displaying the results.

**Comment by benjaminantieau** [comment]
Sam suggests we abstract the testing functionality and leave that in persispy, but split off the actual test we run into a separate package. Maybe that should just be a Dropbox folder.

**Comment by callmetaste** [comment]
I believe this functionality is done. It's set aside in persispy/tests/test_connected_components.py until I can decide a better name and home for it.
